style: github
template: CHANGELOG.tpl.md
info:
  title: 
  repository_url: https://github.com/dronestock/changelog
options:
  commits:
    filters:
      Type: 
        - feat
        - fix
        - pref
        - refactor
        - chore
  commit_groups:
    title_maps:
      feat: âœ¨ Features | æ–°åŠŸèƒ½
      fix: ğŸ› Bug Fixes | Bugä¿®å¤
      perf: âš¡ Performance Improvements | æ€§èƒ½ä¼˜åŒ–
      refactor: â™» Code Refactoring | ä»£ç é‡æ„
      chore: ğŸ“¦ Chores | å…¶ä»–æ›´æ–°
  header:
    pattern: ^(\w*)(?:\((.*)\))?\:\s(.*)$
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
